import streamlit as st

st.title("Resume Builder - Simple Version")

name = st.text_input("Name")
email = st.text_input("Email") 
phone = st.text_input("Phone")
skills = st.text_area("Skills - comma se alag karke likho")
experience = st.text_area("Experience")

if st.button("Resume Banao"):
    if name and email:
        resume_text = f"""
RESUME
==================

Name: {name}
Email: {email}
Phone: {phone}

SKILLS
------------------
{skills}

EXPERIENCE  
------------------
{experience}

==================
Generated by Streamlit App
"""
        
        st.success("Resume should be done!download it")
        st.download_button(
            label="📥 Download Resume as TXT",
            data=resume_text,
            file_name="resume.txt",
            mime="text/plain"
        )
        st.subheader("Preview:")
        st.text(resume_text)
    else:
        st.error("fill name and e-mail")
